name: Release Please
run-name: ${{ github.actor }} released ${{ github.event.release.tag_name }}
# Full documentation available at: https://github.com/google-github-actions/release-please-action

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.MY_RELEASE_PLEASE_TOKEN }}
          release-type: simple
